global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - scheme: https
    basic_auth:
      username: admin
      password: password
    tls_config:
      ca_file: monitor.harms-devops.ru.crt
    static_configs:
    - targets: ['monitor.harms-devops.ru:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - rules.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus-monitor'
    scheme: https
    basic_auth:
      username: admin
      password: password
    tls_config:
      ca_file: monitor.harms-devops.ru.crt
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['monitor.harms-devops.ru:9090']

  - job_name: 'node-monitor'
    scheme: https
    basic_auth:
      username: admin
      password: password
    tls_config:
      ca_file: monitor.harms-devops.ru.crt
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['monitor.harms-devops.ru:9100']

  - job_name: 'node-ca'
    scheme: https
    basic_auth:
      username: admin
      password: password
    tls_config:
      ca_file: ca.harms-devops.ru.crt
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: [ 'ca.harms-devops.ru:9100' ]

  - job_name: 'node-openvpn'
    scheme: https
    basic_auth:
      username: admin
      password: password
    tls_config:
      ca_file: openvpn.harms-devops.ru.crt
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: [ 'openvpn.harms-devops.ru:9100' ]

  - job_name: 'openvpn'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['openvpn.harms-devops.ru:9176']

  - job_name: 'node-backup'
    scheme: https
    basic_auth:
      username: admin
      password: password
    tls_config:
      ca_file: backup.harms-devops.ru.crt
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: [ 'backup.harms-devops.ru:9100' ]


