scrape_configs:
  - job_name: 'prometheus-monitor'
    scheme: https
    basic_auth:
      username: admin
      password: password
    tls_config:
      ca_file: monitor.harms-devops.ru.crt
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['monitor.harms-devops.ru:9090']

  - job_name: 'node-monitor'
    scheme: https
    basic_auth:
      username: admin
      password: password
    tls_config:
      ca_file: monitor.justnikobird.ru.crt
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['monitor.harms-devops.ru:9100']

  - job_name: 'node-ca'
    scheme: https
    basic_auth:
      username: admin
      password: password
    tls_config:
      ca_file: ca.harms-devops.ru.crt
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: [ 'ca.harms-devops.ru:9100' ]

  - job_name: 'node-openvpn'
    scheme: https
    basic_auth:
      username: admin
      password: password
    tls_config:
      ca_file: vpn.harms-devops.ru.crt
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: [ 'vpn.harms-devops.ru:9100' ]

  - job_name: 'openvpn'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['vpn.harms-devops.ru:9176']

  - job_name: 'node-backup'
    scheme: https
    basic_auth:
      username: admin
      password: password
    tls_config:
      ca_file: repo.harms-devops.ru.crt
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: [ 'backup.harms-devops.ru:9100' ]

